"""
This type stub file was generated by pyright.
"""

class Mover:
    def __init__(self, **kwargs) -> None: # type: ignore
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def move_files(self) -> None:
        ...
    


