"""
This type stub file was generated by pyright.
"""

from .rename_config import RenameConfig

class MoverConfig:
    def __init__(self, **kwargs) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def mover_name(self) -> str:
        ...
    
    @property
    def mover_description(self) -> str:
        ...
    
    @property
    def source_directories(self) -> list | None:
        ...
    
    @property
    def file_types(self) -> list | None:
        ...
    
    @property
    def file_type_regex(self) -> str | None:
        ...
    
    @property
    def file_type_exclude_regex(self) -> str | None:
        ...
    
    @property
    def file_names(self) -> list | None:
        ...
    
    @property
    def file_name_regex(self) -> str | None:
        ...
    
    @property
    def file_name_exclude_regex(self) -> str | None:
        ...
    
    @property
    def file_name_contains(self) -> str | None:
        ...
    
    @property
    def file_name_starts_with(self) -> str | None:
        ...
    
    @property
    def file_name_ends_with(self) -> str | None:
        ...
    
    @property
    def destination_directories(self) -> list | None:
        ...
    
    @property
    def rename_config(self) -> RenameConfig | None:
        ...
    
    @property
    def keep_source(self) -> bool:
        ...

    @property
    def recursive(self) -> bool:
        ...


