"""
This type stub file was generated by pyright.
"""

from enum import Enum

class RenameRule:
    def __init__(self, search: str, replace: str) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class TimestampPosition(Enum):
    START = ...
    AFTER_PREFIX = ...
    BEFORE_SUFFIX = ...
    END = ...
    @classmethod
    def from_string(cls, position: str) -> TimestampPosition:
        ...
    


class AddTimestampConfig:
    def __init__(self, **kwargs) -> None:
        ...
    
    @property
    def enabled(self) -> bool:
        ...
    
    @property
    def position(self) -> TimestampPosition:
        ...
    
    def get_timestamp(self): # -> str:
        ...
    


class RenameConfig:
    def __init__(self, **kwargs) -> None:
        ...
    
    @property
    def enabled(self) -> bool:
        ...
    
    @property
    def replace_rules(self) -> list[RenameRule]:
        ...
    
    @property
    def case_sensitive(self) -> bool:
        ...
    
    @property
    def prefix(self) -> str:
        ...
    
    @property
    def suffix(self) -> str:
        ...
    
    @property
    def add_timestamp(self) -> AddTimestampConfig:
        ...
    
    def apply_rename(self, file_name: str) -> str:
        ...
    


